---
settings:
  general_category:
    minimalist:
    maximum_percent:
      default: 50
      type: integer
      description: The minimum percentage to pass
    difficulty:
      options: 'easy normal hard'
    product_ids:
      type: csv
      subtype: integer
      default: '1,2,3'
    testing:
      type: boolean
      default: 'true'
